// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoCgiUYh84mocHdgPvun-StJG1qaVHyM',
    appId: '1:599374891802:web:1f41bdb7bf3621a9f77aa3',
    messagingSenderId: '599374891802',
    projectId: 'attendease-6b6a9',
    authDomain: 'attendease-6b6a9.firebaseapp.com',
    storageBucket: 'attendease-6b6a9.firebasestorage.app',
    measurementId: 'G-1NXTSM8LED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfikt2ae5eklkR5yiOlUvYlFNpoziFwU',
    appId: '1:599374891802:android:2e57a150dc042a83f77aa3',
    messagingSenderId: '599374891802',
    projectId: 'attendease-6b6a9',
    storageBucket: 'attendease-6b6a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rXXL1bnFW9N12Eyk0hDb8ZGx2GH06IU',
    appId: '1:599374891802:ios:9af6c8a66d6ef68df77aa3',
    messagingSenderId: '599374891802',
    projectId: 'attendease-6b6a9',
    storageBucket: 'attendease-6b6a9.firebasestorage.app',
    iosBundleId: 'com.example.attendease',
  );
}
